### ISSUE TITLE
Discuss calibration steps 

### ISSUE THREAD

**Issue by jradcliffe5** [e-merlin/eMERLIN_CASA_pipeline#30]
Javier and I have the basis of the pipeline almost ready. We now need to get everyone's help in setting out best calibration steps in order to make the pipeline as good as it can be. Thanks to Javier, it should now work on any machine (minus flagging if you dont have aoflagger)

I propose that we have a telecon/skype soon in order to discuss how we are going to proceed, map out a plan for the calibration steps + how we are going to split the workload.

**Comment by jmoldon** [comment]
These are the main four calibration blocks. Feel free to comment here if you want to modify something of the general structure or in the individual issues to discuss details of each step.

- [ ] Delay and Preliminary BandPass calibration  #31
-- Calibrate **delays** of calibrators 
-- Calibrate **phases** of BP calibrator
-- Calibrate **A&P** of BP calibrator
-- Initial **BP** table
-- Additional flags on BP calibrator
-- Plots

- [ ] Preliminary calibration #32
-- Calibrate **phases** of calibrators
-- Calibrate **A&P** of calibrators
-- Additional flags
-- Plots

- [ ] Amplitude scale #33
-- Fluxscale
-- dfluxpy
-- setjy
-- Plots

- [ ] Final calibration #34
-- **BP** with spectral index information
-- **Phase** calibration
-- **A&P** calibration
-- Applycal
-- Plots

**Comment by jradcliffe5** [comment]
We should also have an issue for self calibration. It's sometimes vital on faint phase calibrators. A multipurpose function for this will be the best so that we can use it for both target & and phase cals. @amsrichards sounds like something you may have already?

**Comment by amsrichards** [comment]
Thanks Jack, Javier

I think that we need to get the pipeline working for a simple case first... a straightforward C-band point phse-ref! I am not quite sure what Jack is referring to:


"We should also have an issue for self calibration. It's sometimes vital on faint phase calibrators. A multipurpose function for this will be the best so that we can use it for both target & and phase cals."


Some cases I can think of - but maybe Jack had something else in mind?  Also, minor deficiencies in the phase-ref are often not important for self-cal'able targets - but obviously they are for faint ones, or if you want very accurate astrometry/photometry...


1) The initial S/N of the phase-ref is poor, owing to phase errors rather than intrinsic faintness, and so the amplitude is depressed.  One thing which ALMA does which maybe we could consider, is using a very short solint for an initial phase-only calibration of the calibrator sources.  This is applied in order to derive the amplitude solutions on the timescale of a scan (for the phase-ref). Then another phase-only table on a timescale of a scan or half a scan is derived on the phase-ref specifically to apply to the target.


2) If the phase-ref is point-like but intrinsically faint, then traditional self-calibration is of limited use... self-calibration being defined as repetative calibration and imaging, at each step either the model is improved (but you can't improve on a genuine point) or the solint is reduced - but we are restricted in the options for meaningful phase transfer to the target... if we adopt procedure 1) as normal then for intrinsically faint phase refs we could revert to per-scan solutions in all gaincals including the initial 'p'... Pierre was convinced that iterative self-cal on a point imprroved the solutions but I don't understand that (unless something else is happening, like you are calibrating the weights or flagging failed solutions, but if that continues to change in multiple iterations then probably something is wrong and your flux scale is floating...) - e.g. one could check for more than 5 or 10% failed solutions on a short solint gaincal, and/or low S/N on a phase ref image, and summon a human (or once we are very sure of ourselves, revert to per scan solint automatically....)


3) Unconfused but possibly resolved phase-ref: amp v. uvdistance plot - the Bologna node wrote a routine to compare the quartiles (or possibly deciles) of th distribution with a diagnostic for possible resolution ie. more flux on short baselines.  Possibly have to be implemented sans Defford at C-band because its high rms can be misleading (test?) - https://wikis.alma.cl/twiki/pub/CSV/WeakCalibratorReduction/aa_Pies_17032017.tar  in the code for weak_calibrator_reduction3.9.3.py step 10 does this (although the basl_range is hard-wired for ALMA, but at least e-M doesn't reconfigure!).

Also an image of the centre of the field for human inspection - since we can pretty quickly spot a resolved source v. amp or phase errors mimicking this. I think that probably this is best implemented as a potential break point, so that a human could then build up a nice model of the phase-ref and there could eventually be a pipeline option to accept a model (as for 3C286) - even a library of models :-)


4) Confusion - usually only at L-band.   This can be hard to spot even in uv plots if the confusion is far away and so decorrelated if plotted wrt phase centre.  Does the VLA  CASA pipeline know how to query NVSS? It might be useful just to pull up a list of all NVSS sources within the primary beam above some threshold (maybe adaptive depending on where in the PB) and make postage stamp images at the position for a human to decide if they need to be included in a model.


But, I don't know of anyone who has successfully automated self-cal except in special cases, e.g. Phil Diamond's SiO VLBI script, where the data sets were small enough that you could find the brightest channel and do 10 rounds of blind self-cal ...


cheers

a

**Comment by jradcliffe5** [comment]
I'm not sure what I meant either re-reading it... I always think that self-calibration can be automated but that may be a PhD in itself when I look at it... I think I was coming from the VLBI point of view where we often have to self-calibrate the phase reference sources. 

I think it may be worth doing point 1) either way within the pipeline (after testing ofc). 

3 & 4) Having the tests for resolved phase calibrators and query bright sources should be included though. Would be extremely useful in the future. 

wrt 4) As far as I can tell, the VLA pipeline does not query NVSS/FIRST but the CASA vo toolkit can do this right? W.r.t. to adaptive search we need PB models as it depends source flux, frequency and radius (i.e. primary beam attenuation). That's another thing actually, is there a way to get e-MERLIN into the accepted telescopes for CASA @amsrichards ? I cannot do listobs without it crashing out in CASA v4.7.2

**Comment by amsrichards** [comment]
Hi Jack,

I am currently on a rather slow link so can't check (as I ahve not got 4.7.2 on my laptop yet) but if you use browsetable to look at the equivalent of

CASA/casa-release-4.7.1-el6/data/geodetic/Observatories
you should see e-MERLIN in there (NB quite near the bottom, not alphabetical for all), that is all that CASA can do.  If you are having problems in 4.7.2:

1) Is it a data set imported directly from fitsidi to MS?  Going through uvfits i.e. aips is known to mess up observatory recognition.

2) Even if so, there was at one time a bug which affected data which had been split, or possibly all data on the Mac version of CASA.  The ERIS 2015 cal script had
# Fix for CASA 4.4 (not needed in 4.5)
    tb.open('1252+5634.ms',nomodify=F)
    SIDorig=tb.getcol('STATE_ID')
    SID=SIDorig*0
    SIDnew=SID-1
    tb.putcol('STATE_ID',SIDnew)
    tb.close()


3) Have you tried a data set which worked OK in an earlier CASA?

If there is a problem with data which are innocent of AIPS and which worked in an earlier version of CASA, please can you send me all the details, command inputs. error messages etc?

thanks and sorry for the hassles
Anita


--------------------------------------------------------------------------------------------------------
Dr. A.M.S. Richards, UK ARC Node, Room 3.136, JBCA, Alan Turing Building,
University of Manchester, M13 9PL +44 (0)161 275 4243
and
MERLIN/VLBI National Facility,  JBO, SK11 9DL, U.K. +44 (0)1477 571321 (tel) 571618 (fax)

________________________________

**Comment by jmoldon** [comment]
My situation with listobs is the following (using an MS from FITSIDI directly and CASA version 4.7.2 but also others):
- Running with default parameters it shows: general information, list of scans, fields, spectral windows, and then tries to show the antennas info (ID, name, Diam., Long, Lat., Offset) but crashes:
`2017-04-13 11:00:37 SEVERE listobs	Exception Reported: Exception: Telescope e-MERLIN is not recognized by CASA.`
- With that configuration if I try to put the output in a file with listfile, it crashes as before but the whole CASA crashes with a segmentation fault!
- If I use verbose = False, then it works well but does not show all the information. You only see: fields, spectral windows and antenna names. It does not crash, and I can output to a file, but there is information missing (in particular the scan list).

- Also, msoverview gives a similar result: OK with verbose=False, and crashes with verbose=True. 
`Error: Exception: Telescope e-MERLIN is not recognized by CASA.`

The problem is probably that e-MERLIN is recognized as an array, but CASA cannot find information about the antennas. That information is in the AN so it seems to be lost somewhere.

**Comment by jmoldon** [comment]
OK, I have solved the problem in my case at least. In fact, the MS does indeed contain the antenna table with all the information (offset, position, type, dish_diameter, mount, name, etc), so the table is not lost.

My problem was that in the file `.casarc` I had a manual definition:
`measures.directory: /usr/local/lofar-2_15/source/casarest-1.4.1/measures_data/`
Needed for LOFAR. That made the measures path to be different from the CASA directory, and that is why it was not finding the array.

I suggest you check your .casarc to see if you have a different definition of measures

**Comment by jradcliffe5** [comment]
Ahhhhhhhhhhhh LOFAR!!!!! my .casarc file had the measures from LOFAR in also, so Javier's fix worked. I'll add this to a common problems page on the wiki so everyone can see this. 

Thanks Anita & Javier!
