### ISSUE TITLE
plotms not closing properly

### ISSUE THREAD

**Issue by varenius** [e-merlin/eMERLIN_CASA_pipeline#76]
Running the pipeline v0.6.2, github last commit: f551150, to produce plots (which are very nice) it ends with this output:

2017-11-08 10:46:03 | INFO | Baseline: Da&Cm , Output: ./plots/plots_data/TSARP220_C_20171013_avg_4plot_1534+2330_Da-Cm_data.png
NOTICE: Exporting to images in screen resolution is currently not working.  Switching to high resolution (which is slower, but works).
2017-11-08 10:49:34 | INFO | Pipeline finished
2017-11-08 10:49:34 | INFO | #################
[emerlin@embe1 TSARP220_20171013]$ 
(casaplotms:28397): GConf-WARNING **: Got Disconnected from DBus.

Perhaps casaplotms is not closed (or killed) in the right way before finishing the pipeline?

**Comment by jmoldon** [comment]
I don't see that warning after running plotms, we can check if it appears in other computers, or when connected remotely, etc. Do you see any consequences? like any plots missing, or some window left opened?

[If you are at that stage of the pipeline, I recommend you use the new v0.6.3 updated yesterday. It produces much better plots of the calibration tables using plotms instead of plotcal, which is quite terrible. It will also put a lot of information on the calibration steps and those plots in a new tab in the weblog. If you started with v0.6.2, remove all the pkl files in the main forlder and in ./calib/ before running newer versions, because there are a few additions to those pickle files that the weblog needs. And of course, to have the new calibration plots you will need to run the corresponding calibration steps again.]

**Comment by jmoldon** [comment]
Resolved by #100
