### ISSUE TITLE
Potential speed up when making mms & hanning smoothing

### ISSUE THREAD

**Issue by jradcliffe5** [e-merlin/eMERLIN_CASA_pipeline#97]
Hi Javier, 

Was just using the pipeline and thought it may be quicker to do the mms step & hanning smoothing step together using just mstransform? 

I'm not sure whether you've tested this or not

**Comment by jmoldon** [comment]
Yes, I'm reviewing the performance of that part of the code. The obvious thing I was going to do is to change the order of hanning and ms2mms, currently hanning happens before, which makes no sense. Hanning is much faster  just by doing it after mms: from 1h to just 7-8min.

Including both in a single step is a good idea because I have not seen any case in which you really needed to check or modify any of those straightforward transformations. Will do that.

**Comment by jmoldon** [comment]
Resolved by #100
